ServerEvents.tags("item", event => {
    event.get("jcy:mechanism")
        .add([
            "jcy:wooden_mechanism",
            "jcy:infernal_mechanism",
            "jcy:stone_mechanism",
            "jcy:iron_mechanism",
            "jcy:copper_mechanism",
            "jcy:andesite_mechanism",
            "jcy:mechanism_thermal",
            "jcy:resonant_mechanism",
            "jcy:reinforced_mechanism",
            "jcy:gold_mechanism",
            "jcy:smart_mechanism",
            "jcy:better_mechanism_precision",
            "jcy:mechanism_bronze",
            'create:precision_mechanism',
            'vintage:redstone_module',
            'jcy:thermal_mechanism',
            'jcy:bronze_mechanism'
        ])
    event.get("jcy:mechanism_incomplete")
        .add([
            "jcy:wooden_mechanism_incomplete",
            "jcy:infernal_mechanism_incomplete",
            "jcy:stone_mechanism_incomplete",
            "jcy:iron_mechanism_incomplete",
            "jcy:copper_mechanism_incomplete",
            "jcy:andesite_mechanism_incomplete",
            "jcy:mechanism_thermal_incomplete",
            "jcy:resonant_mechanism_incomplete",
            "jcy:reinforced_mechanism_incomplete",
            "jcy:gold_mechanism_incomplete",
            "jcy:smart_mechanism_incomplete",
            "jcy:mechanism_bronze_incomplete",
            'create:incomplete_precision_mechanism',
            'vintage:incomplete_redstone_module',
            'jcy:thermal_mechanism_incomplete',
            'jcy:bronze_mechanism_incomplete'
        ])
    event.get("jcy:prat")
        .add([
            'jcy:basic_part',
            "jcy:mechanism_part",
            "jcy:flux_part"
        ])
})